_default:
    methods: [ GET ]
    path: /
    controller: App\Controller\Shared\HelloWorldController

_default_api:
    methods: [ GET ]
    path: /api
    controller: App\Controller\Shared\HelloWorldController